/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.gui;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import ufps.negocio.SistemaHTML;
import java.io.FileReader;
import java.io.FileWriter;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;
import ufps.negocio.ErrorHTML;
import ufps.negocio.TextLineNumber;
import ufps.util.ArchivoLeerURL;
import ufps.util.ExceptionUFPS;
import ufps.util.Pila;

/**
 *
 * @author Leonar
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    // http://slwox.com/pagina.html
    private JTextArea txtEditor = new JTextArea();
    private final String dir = "file:///C:/Users/Leonar/Desktop/html_w3c.txt";
    Object v[] = null;
    private SistemaHTML sistema;

//    String vBasic[] = null;
//    String vFormatting[] = new String[37];
//    String vForms[] = new String[12];
    public FormPrincipal() {
        try {
            this.sistema = new SistemaHTML();
        } catch (ExceptionUFPS ufps) {
            System.out.println(ufps);
        }

        initComponents();
        this.setResizable(false);

        this.setLocationRelativeTo(null);
        this.crearTextArea();
        this.crearIconButton();

        ArchivoLeerURL file = new ArchivoLeerURL(dir);
        v = file.leerArchivo();
        String aux = "";
        String datos[];
        this.comboTipoEtiqueta.addItem("Seleccione el Tipo...");
        for (Object dato : v) {
            datos = dato.toString().split(";");
            if (datos[0] == null ? aux != null : !datos[0].equals(aux)) {
                this.comboTipoEtiqueta.addItem(datos[0]);
                aux = datos[0];
            }
        }

    }

    /**
     * Metodo que permite cargar los respectivos items, para luego guardar los
     * nombres de las etiquetas
     *
     * @param c
     */
    private void cargarItems(JComboBox c) {
        this.comboNomEtiqueta.removeAllItems();
        int n = c.getSelectedIndex();
        String datos[];

        this.comboNomEtiqueta.addItem("Seleccione la Etiqueta...");
        for (Object dato : v) {
            datos = dato.toString().split(";");
            if (c.getItemAt(n).equals(datos[0]) && !c.getItemAt(n).equals("Seleccione el Tipo...")) {
                if (datos[1].equals("<html>")) {
                    this.comboNomEtiqueta.addItem("\t<html>");
                } else if (datos[1].equals("<h1> to <h6>")) {
                    for (int i = 1; i <= 6; i++) {
                        this.comboNomEtiqueta.addItem("<h" + i + ">");
                    }
                } else if (datos[1].equals("<!--...-->")) {
                } else {
                    this.comboNomEtiqueta.addItem(datos[1]);
                }

            }
        }
    }

    /**
     * Metodo que permite insertar las etiquetas en el editor
     *
     * @param etiqueta
     */
    private void insertarEtiqueta(String etiqueta) {

        String eti;
        String aux = etiqueta.substring(0, 1);
        String d = "";
        for (int i = 1; i < etiqueta.length(); i++) {
            d += etiqueta.charAt(i);
        }
        eti = aux + "/" + d;
        txtEditor.insert(etiqueta + "\n" + eti + "\n", txtEditor.getCaretPosition());
    }

    private void crearIconButton() {
        ImageIcon img = new ImageIcon(getClass().getResource("/ufps/imagen/icon_ayudaHTML.png"));
        ImageIcon img1 = new ImageIcon(getClass().getResource("/ufps/imagen/icon_ayudaHTML1.png"));
        btnAyudasHTML.setIcon((Icon) img);
        btnAyudasHTML.setPressedIcon(img1);
    }

    private void crearTextArea() {
        JScrollPane scrollPane = new JScrollPane(this.txtEditor);
        TextLineNumber tln = new TextLineNumber(this.txtEditor);
        scrollPane.setRowHeaderView(tln);
        scrollPane.setBounds(3, 120, 550, 500);
        add(scrollPane);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboTipoEtiqueta = new javax.swing.JComboBox();
        comboNomEtiqueta = new javax.swing.JComboBox();
        btnAyudasHTML = new javax.swing.JButton();
        btnValidar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnArchivoPC = new javax.swing.JButton();
        textFileURL = new javax.swing.JTextField();
        btnArchivoWeb = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(802, 650));
        setMinimumSize(new java.awt.Dimension(802, 650));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/imagen/banner.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Etiquetas HTML", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setMaximumSize(new java.awt.Dimension(227, 140));
        jPanel1.setMinimumSize(new java.awt.Dimension(227, 140));

        comboTipoEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoEtiquetaActionPerformed(evt);
            }
        });

        comboNomEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNomEtiquetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTipoEtiqueta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboNomEtiqueta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(comboTipoEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboNomEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnAyudasHTML.setBorder(null);
        btnAyudasHTML.setBorderPainted(false);
        btnAyudasHTML.setContentAreaFilled(false);
        btnAyudasHTML.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyudasHTML.setFocusPainted(false);
        btnAyudasHTML.setFocusable(false);
        btnAyudasHTML.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAyudasHTML.setRequestFocusEnabled(false);
        btnAyudasHTML.setRolloverEnabled(false);
        btnAyudasHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudasHTMLActionPerformed(evt);
            }
        });

        btnValidar.setText("Validar y Guardar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cargar HTML", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setMaximumSize(new java.awt.Dimension(227, 170));
        jPanel2.setMinimumSize(new java.awt.Dimension(227, 170));
        jPanel2.setPreferredSize(new java.awt.Dimension(227, 170));

        btnArchivoPC.setText("Cargar archivo del computador");
        btnArchivoPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoPCActionPerformed(evt);
            }
        });

        textFileURL.setText("http://slwox.com/pagina.html");
        textFileURL.setToolTipText("Ingresa la URL del sitio");
        textFileURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFileURLActionPerformed(evt);
            }
        });

        btnArchivoWeb.setText("Cargar desde sitio web");
        btnArchivoWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFileURL)
                    .addComponent(btnArchivoWeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(btnArchivoPC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnArchivoPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFileURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArchivoWeb)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAyudasHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAyudasHTML, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnValidar)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArchivoPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoPCActionPerformed
        // TODO add your handling code here:
        try {

            BufferedReader entrada;
            String codigo = "";

            JFileChooser input = new JFileChooser();
            input.setMultiSelectionEnabled(false);
            input.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter filter = new FileNameExtensionFilter("HTML files", "html", "htm");
            input.setFileFilter(filter);

            input.setAcceptAllFileFilterUsed(false);

            int result = input.showSaveDialog(this);

            if (result == JFileChooser.APPROVE_OPTION) {
                File f = input.getSelectedFile();
                entrada = new BufferedReader(new FileReader(f));
                while (entrada.ready()) {
                    codigo += entrada.readLine() + "\n";
                }
                this.txtEditor.setText(codigo);
            } else if (result == JFileChooser.CANCEL_OPTION) {
            }

        } catch (Exception ufps) {
            System.out.println(ufps.getMessage());
        }
    }//GEN-LAST:event_btnArchivoPCActionPerformed

    private void btnArchivoWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoWebActionPerformed
        // TODO add your handling code here:

        try {
            String dir = this.textFileURL.getText();
            String[] vec = dir.split("\\.");
            this.textFileURL.setText(dir);

            ArchivoLeerURL file = new ArchivoLeerURL(dir);
            Object v[] = file.leerArchivo();
            String codigo = "";
            for (Object dato : v) {
                codigo += dato + "\n";
            }
            this.txtEditor.setText(codigo);

        } catch (Exception ufps) {
            System.out.println(ufps.getMessage());
        }
    }//GEN-LAST:event_btnArchivoWebActionPerformed

    private void btnAyudasHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudasHTMLActionPerformed
        // TODO add your handling code here:
        DialogFormAyudasHTML d = new DialogFormAyudasHTML(new javax.swing.JFrame(), true);
        d.setVisible(true);
    }//GEN-LAST:event_btnAyudasHTMLActionPerformed

    private void comboTipoEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoEtiquetaActionPerformed
        // TODO add your handling code here:

        this.cargarItems(this.comboTipoEtiqueta);

    }//GEN-LAST:event_comboTipoEtiquetaActionPerformed

    private void comboNomEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNomEtiquetaActionPerformed
        // TODO add your handling code here:
        int n = this.comboNomEtiqueta.getSelectedIndex();
        if (this.comboNomEtiqueta.getItemAt(n) != "Seleccione la Etiqueta...") {
            if (this.comboNomEtiqueta.getItemAt(n) != null) {
                this.insertarEtiqueta(this.comboNomEtiqueta.getItemAt(n) + "");
            }
        }
    }//GEN-LAST:event_comboNomEtiquetaActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:

        try {
            this.sistema.cargarCodigoFuente(this.txtEditor.getText());
            this.sistema.validarHTML();

            Pila<ErrorHTML> p;
            p = sistema.retornarPila();
            String datos[][] = new String[p.getSize()][2];

            int i = 0;
            while (!p.esVacio()) {
                ErrorHTML e = p.pop();
                datos[i][0] = e.getMyEtiqueta().getEtiqueta() + "";
                datos[i][1] = e.getMyError().getDescripcion() + "";
                i++;
                System.out.println(e.getMyEtiqueta().getEtiqueta() + " " + e.getMyError().getDescripcion());
            }
            if (datos.length >= 1) {
                DialogErroresHTML d = new DialogErroresHTML(datos);
                d.setVisible(true);
            } else {

                JOptionPane.showMessageDialog(this, "No se encontro ningun error en el archivo. \nProcede a guardar el archivo.");

                try {

                    JFileChooser input = new JFileChooser();
                    FileNameExtensionFilter filter = new FileNameExtensionFilter("HTML files", "html", "htm");
                    input.setFileFilter(filter);
                    input.setAcceptAllFileFilterUsed(false);
                    int result = input.showSaveDialog(this);
                    if (result == JFileChooser.APPROVE_OPTION) {
                        File f = input.getSelectedFile();

                        FileWriter fw = new FileWriter(f + ".html");
                        fw.write(this.txtEditor.getText());
                        fw.close();

                    } else if (result == JFileChooser.CANCEL_OPTION) {
                    }

                } catch (Exception ufps) {
                    System.out.println(ufps.getMessage());
                }
            }
        } catch (ExceptionUFPS ufps) {
            System.out.println(ufps);
        }

    }//GEN-LAST:event_btnValidarActionPerformed

    private void textFileURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFileURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFileURLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivoPC;
    private javax.swing.JButton btnArchivoWeb;
    private javax.swing.JButton btnAyudasHTML;
    private javax.swing.JButton btnValidar;
    private javax.swing.JComboBox comboNomEtiqueta;
    private javax.swing.JComboBox comboTipoEtiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textFileURL;
    // End of variables declaration//GEN-END:variables
}
